import { Header } from "@/components/Header";
import { Sidebar } from "@/components/Sidebar";
import type { Metadata } from "next";
import '../globals.css'

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="w-full h-4/5">
        <Header />
        
        <div className="text-white w-full flex items-center px-10 h-full gap-4">
            <Sidebar />

            <main className="flex-1 h-full">
                {children}
            </main>
        </div>
    </div>
  );
}
